### ISSUE TITLE
run classifier model for ce metrics

### ISSUE THREAD

**Issue by farrell236** [ibrahimethemhamamci/CT2Rep#21]
Hi @ibrahimethemhamamci, @sezginerr! Thank you for putting together such a great work! I have a question regarding the BERT model used to predict disease classes as described in the paper. 

Do you have example code how to run it (i.e. the tokenization process, class label ordering of the output)? And is this the weights for the model? https://huggingface.co/datasets/ibrahimhamamci/CT-RATE/blob/main/models/RadBertClassifier.pth

Thanks again!

**Comment by ibrahimethemhamamci** [comment]
Hello @farrell236,

Thank you so much for your kind words!

Yes, we utilized the same RadBERT model with CT-RATE, though this version was fine-tuned on a smaller subset compared to the one used in CT-CLIP. For better performance, please use these model weights: [RadBERT Classifier Weights](https://huggingface.co/datasets/ibrahimhamamci/CT-RATE/blob/main/models/RadBertClassifier.pth).

For the implementation details, you can find the code here: [RadBERT Text Classifier](https://github.com/ibrahimethemhamamci/CT-CLIP/tree/main/text_classifier).

Please let me know if anything else is needed. Thank you again for your kind words and interest!

Best,  
Ibrahim

**Comment by farrell236** [comment]
Thanks @ibrahimethemhamamci, will give the code a try :)
