### ISSUE TITLE
 How to change single gpu training to multi gpu training?

### ISSUE THREAD

**Issue by 1benv** [ibrahimethemhamamci/CT2Rep#8]
self.model = torch.nn.DataParallel(model, device_ids=device_ids)
I change device_ids=[0,6] or [6,5,7] instead of device_ids=range(n_gpus)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:6 and cuda:0! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

it always says tensors not be on the same device,but it has so many cuda code  , how can i change single gpu training to multi gpu training?
<img width="237" alt="12e7ea1a3ce68be4f1b6a279bd5ff990" src="https://github.com/ibrahimethemhamamci/CT2Rep/assets/87710971/48d0eecf-bbaa-407d-b23a-cb353934a54a">

**Comment by hari3100** [comment]
Hi @1benv  , I hope you are doing well, I'm commenting in hopes that you have already ran the CT2Rep model on your own system, could you help me with the inference of this model i have a few questions as well regarding the input size, etc.
But the main thing I'm looking for is how can I run the model, I'm new to medical imaging ,and I'm not understanding the code which is already present in the repo, could you maybe share some inference code you wrote, or guide me on how to do it ?....any feedback or guidance will be greatly appreciated...Thank you for your time!
